---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-19 17:19
---

function fprint(fm, ...)
    io.write(string.format(fm, ...))--string.format的使用
end
fprint("age=%d, name=%s", 10, "miao")

print()

for i = 1, 10 do
    local s = string.rep("*", i)--复制i次“a"
    print(s)
end

