---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-20 17:49
--- 双端队列, table={first=-1, last=0, 1, 2, 3, 4, 5}first不断加1， last不断减1，用first和last存储当前指针到哪了

Queue = {}
function Queue.new()
    return {first = -1, last = 0}
end

--向头部插入
function Queue.pushFirst(list, value)
    local first = list.first + 1
    list.first = first
    list[first] = value
end

--向尾部插入
function Queue.pushLast(list, value)
    local last = list.last - 1
    list.last = last
    list[last] = value
end

--从头部获取
function Queue.pollFirst (list)
    local first = list.first
    if first < list.last then
        error{"list is empty"}
    end
    local ret = list[first]
    list.first = list.first - 1
    list[first] = nil
    return ret
end

--从尾部获取
function Queue.pollLast(list)
    local last = list.last
    if last > last.first then error {"list is empty"} end
    local ret = list[last]
    list.last = last + 1
    list[last] = nil
    return ret
end

local myQueue = Queue.new()
Queue.pushFirst(myQueue, 1)
Queue.pushFirst(myQueue, 2)
Queue.pushFirst(myQueue, 3)
for i, v in pairs(myQueue) do
    print(i, v)
end
print("----------------")
Queue.pollFirst(myQueue)
Queue.pollFirst(myQueue)
Queue.pollFirst(myQueue)
print("----------------")
for i, v in pairs(myQueue) do
    print(i, v)
end