---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-21 12:34
---
local count = 0
function Entry (...)---这里像回调函数
    count = count + 1
end
dofile("121Data.lua")
print(count)


