---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-21 15:34
--- 元表， 字符串默认给了一个原表， 其他基本数值没有定义
---可以修改元表来修改一个值的行为， 使其在面对一个非预定义的操作时执行一个指定的操作， 比如两个table相加
print(getmetatable("aa"))
print(getmetatable(1))
print(getmetatable({}))--table初始化的时候不会有元表
