---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-21 16:55
---  table中的元方法 --index
OriginWindown = {}--先定义再复制的方式很较灵活
OriginWindown.default = {x = 0, y = 0, with = 100, hight = 100}
OriginWindown.mt = {}
OriginWindown.new = function (o)
    o = o or {}
    setmetatable(o, OriginWindown.mt)
    OriginWindown.mt.__index = OriginWindown.default
    return o
end

local newWindown = OriginWindown.new({x = 10, y = 20})
print(newWindown.x, newWindown.y, newWindown.with, newWindown.hight)

----含默认值的table: 修改table的默认值（根据key索引不到的时候，返回的默认值是nil, 可以修改元方法来修改这个值）
print("--------------")
local xx = {}
local tt = {a = "a", b = "b"}
tt[xx] = 10--把table当成了一个key, 这个key是一个table
for i, v in pairs(tt) do
    print(i, v)
end
print("------------")
local key = {}
local mt1 = {__index = function(b)--为避免每次都创建一个table, 把这个table拿到setDefault函数的外面来
    return b[key]
end}
function setDefault (t, def)
    t[key] = def
    setmetatable(t, mt1)
end
local t1 = {a = "a"}
setDefault(t1, "null")
print(t1.xxx)






