---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-22 11:40
---  对于一些操作，通常在外面定义一个table, 来表示某些东西比如定义一个 Set = {a = true, b = true}， 可以记录所有声明过的变量
a = "a"
local declared = {}
local mt = {}
function mt.__index(t, k)
    if not declared[k] then
        error("访问了一个未定义的全局变量") --真没想到Error的优先级竟然比断点还要高。这里去掉error断点就能断住了
    end
end
function mt.__newindex (t, k, v)
    print("看已经定义的变量是否还调用这里？")--只有之前未定义的进行定义时才会调用这里
    if not declared[k] then
        local w = debug.getinfo(2, "S").what
        if w ~= "main" then
            error("只能在main块中对全局变量赋值")
        end
        declared[k] = true
    end
    rawset(t, k, v)
end
setmetatable(_G, mt)
print(a)
a = "b"
print(a)
c = "c"
