---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-20 12:19
---类的实现用的是元操作 setmetatable(a, {--index = b}) a 会在 b中查找所有他没有的元素和元素方法。 如果a是个空, 则和b完全一样，所以称为类（实际也包含了继承）

local Account = {
    balance = 0,
    width = 1,
    methord1 = function (self, v)--内部定义
        self.balance = v
    end,
}
function Account:methord2 (v)--外部定义
    self.balance = v
end
Account:methord1(100)
print(Account.balance)
Account:methord2(200)
print(Account.balance)
print("------创建对象--------")
function Account:new(o)
    o = o or {}
    setmetatable(o, self)--设置o的原表为Account
    self.__index = self--不是很明白这个__index是做什么的
    return o
end

local child = Account:new{}
child:methord2(1000)
print(child.balance)
---相当于
Account.methord2(child, 2000)--把child传进去
print(child.balance)
print(child.width)--访问父类的width
