---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-20 14:47
--- --index实现单一继承， 集简易，性能和灵活于一体
---  继承： 子类可以覆盖父类的方法
---污一把吧。定义一个女孩的类(有默认值)
---GirlAa继承GirlA继承Girl

--- ******自定义的元表  setmetatable(t,mt); 表示找不到的时候，再去哪里找*********
----*******在调用table不存在的字段时，会调用__index元方法******
--- ****** 定义元表和设置__index是一起的。 __index可以在外面单独设置，也可以在里面直接设置

---setmetatable(c, {__index = function (t, k)--__index定义成函数时，要有返回值***这是c的元表***
---    return search(allBase, k)
---end})

---setmetatable(another, self)
---self.__index = self--定义到这里却没问题


local Girl = {
    xiongwei = 30,
    yaowei = 20,
    tunwei = 40,
    --__index = self, --定义到这里不行
    yinjiao = function ()
        print("啊啊啊啊啊.....")
    end,
    --提供一个new方法，供后面的继承用
    new = function (self, another)
        another = another or {}
        setmetatable(another, self)
        self.__index = self--定义到这里却没问题    *****在调用table不存在的字段时，会调用__index元方法*****
        return another
    end,
}

--Girl.__index = Girl--定义到这里也没问题
local GirlA = Girl:new()
print(GirlA.yinjiao())
--重写父类方法，用自己的
GirlA.yinjiao = function()
    print("恩啊恩啊恩.....")
end
print(GirlA.yinjiao())

---GirlAa继承GirlA, GirlA继承Girl.  GirlA重写了Girl的淫叫方法
local GirlAa = GirlA:new{}
print(GirlAa.xiongwei)
GirlAa.yinjiao()