---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-20 16:38
---  将原有对象（table）放到闭合函数closure中保护起来，然后提供一个供外面访问的table(俗称调用接口)， 来访问里面的table

function createClass()
    local innerTable = {
        balance = 0
    }
    local addBalance = function (v)
        innerTable.balance = innerTable.balance + v
    end
    local delBalance = function (v)
        innerTable.balance = innerTable.balance - v
    end
    local getBalance = function ()
        return innerTable.balance
    end
    return {
            addBalance = addBalance,
            delBalance = delBalance,
            getBalance = getBalance,
        }
end

local newClass = createClass()
newClass.addBalance(10)
newClass.delBalance(1)
print(newClass.getBalance())

