---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/2/23 8:05
---使用random一定要设置randomseed

---math函数：三角函数（sin, cos, tan, asin, acos等）, 指数和对数函数（exp, log log10）
---取整函数：floor, ceil;  max, min; random, randomseed,
---常量pi, huge

print(math.max(10,9,100,1,1000))
local tt = {1, 2, 3, 4}
print(math.max(table.unpack(tt)))--table.unpack的使用


---一般随机种子只需要设置一次，整个程序运行期间，加载的时候去设置.也一般写封装一个函数
function random ()
    math.randomseed(tonumber(tostring(os.time()):reverse():sub(1, 6)))
    math.random()
end

for i = 1, 10 do
    print(math.random())
end

print("-------------")
for i = 1, 10 do
    print(math.random(10))
end

print("-----------")
for i = 1, 10 do
    print(math.random(90,100))
end

print("--------------")
print(os.time())
math.randomseed(3)--os.time单位是-秒
for i = 1, 10 do
    print(math.random())
end