---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/2/23 9:39
---

local str = "abcDADa"
---获取字符串长度
print(string.len(str))
---都转换成大写或者小写
print(string.lower(str))
print(string.upper(str))
---复制多少次字符串
print(string.rep(str, 10))
--string.rep("a", 2^10)--可以构建一个1MB的字符串
---sub截取
print(str:sub(1, 2))
print(str:sub(2))
print(string.sub(str, 2, -2))
---字符-数字
print(string.char(97))--这里只需输入数字
print(string.char(97), string.char(98))
for i = 1, str:len() do
    print(str:byte(i))--相当于 string.byte(str, i)--打印字符串中第i个字符对应的数值
end
print(string.byte(str, 1, str:len()))
--