---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-22 11:09
---

print"------数字匹配%d+--------"
local str = "abc1 de3fg 1234 567, ', #"
local match = string.gmatch(str, "%d+")
for v in match do
    print(v)
end
print("----字母匹配%a+----")
match = string.gmatch(str, "%a+")
for v in match do
    print(v)
end
print"----字母和数字匹配%w+-----"
match = string.gmatch(str, "%w+")
for v in match do
    print(v)
end
print"----与任意字符匹配%p---"
match = string.gmatch(str, "%p")
for v in match do
    print(v)
end
print"----与空格匹配%s---"
match = string.gmatch(str, "%s")
for v in match do
    print(v)
end
print"-----组合(%w+)=(%w+)-----"
local str2 = "a1=#, c2=d"
match = string.gmatch(str2, "(%w+)=(%w+)")--返回第一个（%w+）
for v in match do
    print(v)
end
print"-----[]匹配字符集，[将多个匹配符组成一个的时候用]--([1-3]+)---"
local str3 = "123456329981"
match = string.gmatch(str3, "([1-3]+)")
for v in match do
    print(v)
end
print"-----[]匹配字符集--[^%a]+---"
local str4 = "123456329981"
match = string.gmatch(str4, "[^%a]+")--直接使用^%a是不起作用的[^%a]要有[]才行
for v in match do
    print(v)
end
print"-----[]匹配字符集--[%w_]+---"
local str4 = "abc_ef_cde sdfsdf sd_a b_c"
match = string.gmatch(str4, "[%w_]+")--表示[数字，字母，下划线]多个
for v in match do
    print(v)
end

print"-----用()进行捕获, 主要用于find方法---"
local str5 = "12absdfsdf123dddd"
print(string.find(str5, "(%a+)"))