---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-3-2 16:55
---

--读取一个文件-一次性读取
function readafileAll (filename)
    local file = assert(io.open(filename, "r"))
    local text = file:read("*all");--全部读取
    print(text)
    file:close()
end

--读取一个文件--分块读取
function readafileBlock (filename)
    local buffsize = 2 ^ 13 --8k
    local file = assert(io.open(filename, "r"))
    while true do
        local line, reset = file:read(buffsize, "*line")
        if not line then
            break
        end
        if reset then
            line = line .. reset .. "\n"
        end
        print("===", line)
    end
end

-- 写入文件
function writeafile(filename)
    local file = assert(io.open(filename, "a"))--追加模式 如果是-w就是清空文件内容再写入
    local text = file:write("*all");
    print(text)
    file:close()
end

-- 综合应用：统计一个文件中的总字符数， 行数， 单词的数量
function readafileStatics (filename)
    local buffsize = 2 ^ 13 --8k
    local file = assert(io.open(filename, "r"))
    local cc, lc, wc = 0, 0, 0 -- 字符数， 行， 单词数
    while true do
        local line, reset = file:read(buffsize, "*line")
        if not line then
            break
        end
        if reset then
            line = line .. reset .. "\n"
        end
        cc = cc + #line -- #line能表示有多少个字符
        --统计单词数, 利用的是string的gsub方法， 利用的是返回的第二个参数t表示替换总次数
        local n, t = string.gsub(line,"%S+", "")
        wc = wc + t
        -- 统计单词数
        n, t = string.gsub(line, "\n", "\n")
        lc = lc + t
    end
    print("字符总数=", cc, ", 单词总数=", wc , ", 行数=", lc)
end

local fileName = "D:/c1.txt"
--readafileBlock(fileName)
--writeafile(fileName)
readafileStatics(fileName)

