---
--- *****Lua 的  pcall方法可以捕获异常，相当于try-catch*****
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2019/10/12 16:38
---

function test_sure ()
    print("I am a test")
end

function test_error ()
    prin("I am a test")
end

local status, errormsg = pcall(test_error) -- 注意：这里的函数只有函数名，没有()
print(status)
print(errormsg)