---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-3-2 14:44
---

function foo ()
    print("hello")
end

local tt = debug.getinfo(foo)
for i, v in pairs(tt) do
    print(i, v)
end

local function myHook ()
    local s = debug.getinfo(2).short_src
    print("------>" , s)
end
debug.sethook(myHook, "l")
foo()