---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-14 16:50
---

---尽可能的使用局部变量，是一种良好的编程风格

foo = "foo"
do
    local a, b = 1, 2--多重赋值
    print(a, b)
    a, b = b, a--可以用来交换两个变量, 很有意思。 lua的函数还可以返回多个值，用这种方式可以接收返回的多个值： local a, b = function()
    print(a, b)
    local foo1 = foo--用一个局部变量存储一个全局常量, 当全局常量发生改变时，这个局部变量不会受影响
    foo = "food"
    print(foo1)
end



