---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-19 18:24
---
--local n = io.read("*number")--当输入不是数字的时候，返回的是nil
--print(n)
--if not n then
--    error("invalid input")
--end
local n = assert(io.read("*number"), "invalid input")
print(n)
print("---------")