---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-18 17:17
---

----就看了一遍代码， 之后完全凭自己理解写出来的， 牛逼！！！----

---带过滤器的生产者和消费者
---过滤器本身也是一个协程
---之前的调用关系是   消费者->唤醒生产者协程获得值
---现在变成  消费者->唤醒过滤器协程，过滤器唤醒生产者协程获得值，把值包装， 再返回给消费者

---生产者
local function producter()
   return coroutine.create(function ()
       for i = 1, 10 do
           coroutine.yield(i)
       end
   end)
end

---过滤器
local function filter(producter)
    return coroutine.create(function ()
        while true do
            local status,  producter_value = coroutine.resume(producter)
            local final_value = "from producter -> " .. producter_value
            coroutine.yield(final_value)
        end
    end)
end

---消费者
local function consumer(filter)
    local status, final_value = coroutine.resume(filter)
    print(final_value)
end

local p = producter()
local f = filter(p)
for i = 1, 10 do
    consumer(f)
end

