---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-14 14:23
---

---指数运算符^
local a = 3 ^ 3; --3的3次方
print(a)

local b = 16 ^ (1 / 2) --开二次方(平方根)
print(b)

local c = 27 ^ (1 / 3) --开三次方（立方根）
print(c)

---取模运算符 %， 用于取小数点后面和前面的数， 以及保留两位小数
local d = 3.14159265358979
print(d % 1)--小数点部分
print(d - d % 1)--整数部分
print(d - d % 0.01)--小数点保留两位（不四舍五入）

---车旋转多少角度可以往回开。一般车旋转180掉头才能往回开， 再加上10的误差， 应该是在(170-190)之间是可以往回开的
local tolerance = 10;--可以容忍10个角度的误差
function isturnback(angle)
    angle = angle % 360
    return (math.abs(angle - 180) < tolerance)
end
print(isturnback(171))



