---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-14 15:07
---

--- and 和 or都遵循短路求值的规则,只有在需要时才评估第二个操作数
---and 如果第一个操作数为false, 则返回第一个操作数， 否则返回第二个操作数
print(nil and 1)
print(false and 1)
print(4 and 5)

---or 如果第一个操作数为true, 则返回第一个操作数， 否则返回第二个操作数
print(4 or 5)
print(nil or 1)
print(false or 1)

---（a and b ） or c 类似java中的 a?b:c
local a = 10
a = a < 0 and 0 or a
print(a)

---not相当于java中的!
print(not(5 > 10))

--[[
    a + i < b / 2 + 1 等价于 (a + i) < ((b / 2) + 1)
    5 + x ^ 2 * 8 等价于 5 + ((x ^ 2) * 8)
    x ^ y ^ z 等价于 x ^ (y ^ z)
]]--
