---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-14 9:28
---
student = {
    ["id"] = 1,
    ["age"] = 10,
    ["name"] = "zhangsan"
}

--取值
print("===取值===")
print(student.id)
print(student.age)
print(student.name)

--遍历一
print("===遍历一===")
for key, value in pairs(student) do--无序的,根据key的hashcode排列的
    local keyAndValue1 = key .. " " .. value--拼接两个变量用..
    print(keyAndValue1)
    local keyAndValue2 = {}--用一个table来组合， 这种方式要比直接使用..快20多倍，因为..每次都开辟新的空间，旧的也不断被GC. 而table使用了算法（栈+二分法）减少了..和GC的次数
    table.insert(keyAndValue2, key)
    table.insert(keyAndValue2, value)
    print(table.concat(keyAndValue2, " "))
end

--后来赋值--
print("--后来赋值--")
teacher = {}
teacher.id = 1
teacher.age = 30
teacher.name = "teacher"
for key, value in pairs(teacher) do
    print(key, value)
end

--初始赋值--
print("--初始赋值--")
xiaozhang = {id = 10, age = 50, name = "xiaozhang", [1] = teacher}
th = xiaozhang[1];
for key, value in pairs(th) do
    print(key, value)
end
print("----")
for key, value in pairs(xiaozhang) do
print(key, value)
end
