---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-14 16:05
---

---第一种方式
local a = {1, "2", 3}

---第二种方式
local b = {
    [1] = 1,
    ["a"] = "a",
}

---第三种方式
local c = {}
c.x = 1
c.y = "b"

---第四种方式
local d = {
    x = "xx",
    [1] = 1;--这个地方的分号也是对的，没什么实际意义，可以做区分用
    {a1 = "a1", a2 = "a2"}--嵌套了一个table
}
print(d[1].a2)

---
local list = nil
list = {
    next = "next",
    value = "value",
}

---table中的value可以是table， key是id, 可以模拟字典表
local e = {}
e[1] = a
e[2] = b
e[3] = c
e[4] = d
