---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wangyu.
--- DateTime: 2019-2-13 17:34
---
tb = {1, 2, 3, "aaaa"}
print(tb[4])
print("=====")
tx = {};
tx["xx"] = "xx1"
tx["yy"] = "yy1"
print(tx["xx"])
print(tx.xx)
print(tx.yy)
print(#tx)
print("=====")
a = {}
for i = 1, 100 do
   a[i] = i * 2
end
print(#a)
a[#a] = nil
print(#a)
a[#a + 1] = 10000
for i = 1, #a do
    print(a[i])
end


